# -*- coding: utf-8 -*-
from pathlib import Path
import textwrap

base_url = "https://mansheudawah.com/pages"

carousel_cards = [
    ("basics-of-islam", "basics-of-islam.html", "Basics of Islam", "Islam is a monotheistic faith founded on the belief in one God (Allah) and the teachings of Prophet Muhammad (peace be upon him). Muslims follow the Five Pillars of Islam and believe in the Quran as the final revelation from God."),
    ("hajj-umrah", "hajj-umrah.html", "Hajj and Umrah", "Hajj is the annual pilgrimage to Mecca that every able-bodied Muslim must perform at least once in their lifetime. Umrah is a shorter pilgrimage performed year-round for spiritual closeness to Allah."),
    ("ramadan", "ramadan.html", "Ramadan", "Ramadan is the ninth month of the Islamic calendar when Muslims fast from dawn to sunset. It is a time of spiritual reflection, prayer, charity, and community gathering, culminating in the celebration of Eid al-Fitr."),
    ("shariah", "shariah.html", "Shariah", "Shariah is Islamic law derived from the Quran and Sunnah. It provides guidance on worship, ethics, family life, and social justice. Shariah emphasizes compassion, fairness, and the protection of human dignity in all aspects of life."),
    ("health-wellness", "health-wellness.html", "Health &amp; Wellness", "Islam teaches that the body is a trust from Allah and must be cared for properly. Muslims are encouraged to maintain physical health through balanced nutrition, exercise, and cleanliness, while also nurturing mental and spiritual well-being."),
    ("charity", "charity.html", "Charity", "Charity is a fundamental principle in Islam. Zakat (obligatory charity) is one of the Five Pillars, while Sadaqah (voluntary charity) is highly encouraged. Giving purifies wealth and helps create a just and compassionate society."),
    ("peace-violence", "peace-violence.html", "Peace &amp; Violence", "Islam promotes peace, justice, and the sanctity of human life. The religion condemns terrorism and unjust violence. True jihad is primarily a spiritual struggle for self-improvement, while physical defense is only permitted in specific, limited circumstances."),
    ("women", "women.html", "Women", "Islam grants women rights to education, property ownership, and spiritual equality with men. Women are honored as mothers, daughters, wives, and professionals. Islamic teachings emphasize respect, dignity, and protection for women in all spheres of life."),
    ("men", "men.html", "Men", "Men in Islam are called to be protectors and maintainers of their families with justice and compassion. Islamic masculinity emphasizes responsibility, humility, emotional intelligence, and service to family and community while striving for personal spiritual growth."),
]

pages = [
    {
        "slug": "charity",
        "title": "Charity",
        "meta_desc": "Learn how zakat, sadaqah, and compassionate giving purify wealth, empower society, and attract Allah's mercy.",
        "share_text": "Charity Insights",
        "qas": [
            ("What does charity mean in Islam?", """<p><strong>Charity is an act of love, justice, and gratitude that proves everything we possess belongs to Allah.</strong> When Muslims give, they acknowledge that wealth is a test and a tool, not an identity, and that true prosperity lies in using it to please the Giver.</p><p>Giving is therefore a spiritual practice as much as it is an economic one. It softens the heart, cures greed, and invites divine mercy in both this life and the Hereafter.</p>"""),
            ("How are zakat and sadaqah different?", """<p><strong>Zakat is the obligatory annual charity that purifies eligible savings once they reach the nisab threshold and a lunar year passes.</strong> It carries precise rates and must be delivered to specific recipients listed in Surah at-Tawbah (9:60).</p><p><strong>Sadaqah is voluntary charity</strong> that can be given anytime, for any amount, and even through non-monetary acts such as a smile, teaching, or removing harm from a pathway. Both feed the soul, yet zakat carries the accountability of a pillar while sadaqah reflects the generosity of an eager heart.</p>"""),
            ("Why is zakat a pillar of Islam?", """<p><strong>Zakat literally means purification and growth.</strong> By giving a portion of our wealth we cleanse the remainder from selfishness and earn the blessing of increase. Allah promises, \"Whatever you give in charity, He will replace\" (Qur'an 34:39).</p><p>Zakat also institutionalizes compassion. It ensures resources circulate rather than stagnate, empowers the vulnerable, and keeps the prophetic community tied together in mutual care.</p>"""),
            ("Who is obligated to pay zakat?", """<p><strong>Every Muslim who owns wealth above the nisab amount for a full lunar year must pay zakat.</strong> Wealth includes cash, investments, business inventory, certain agricultural outputs, and precious metals.</p><p>Nisab is the minimum threshold roughly equivalent to the value of 85 grams of gold. Keeping organized records, tracking anniversaries of ownership, and seeking learned advice guards against negligence.</p>"""),
            ("Who can receive zakat funds?", """<p><strong>The Qur'an lists eight eligible categories:</strong> the poor, the needy, zakat administrators, new Muslims or allies whose hearts are to be reconciled, captives seeking freedom, those drowning in debt, efforts in the path of Allah, and stranded travelers.</p><p>Local scholars or trustworthy organizations can help verify eligibility. The aim is to uplift recipients with dignity, not simply to distribute money.</p>"""),
            ("When should zakat be paid?", """<p><strong>Many Muslims tie zakat to Ramadan for spiritual synergy, but it can be paid at any time once a lunar year elapses on the nisab amount.</strong></p><p>Setting calendar reminders, automating transfers, or splitting payments throughout the year keeps generosity consistent and reduces last-minute rush.</p>"""),
            ("How is zakat calculated on business assets?", """<p><strong>Business owners assess the value of cash on hand, receivables likely to be collected, inventory for sale, and investment holdings at their current market rate.</strong></p><p>They subtract short-term liabilities due within the same period and then apply the zakat rate to the net amount. Consulting Muslim accountants or reputable zakat calculators ensures accuracy.</p>"""),
            ("What is sadaqah jariyah?", """<p><strong>Sadaqah jariyah is ongoing charity whose reward continues long after the donor passes away.</strong> Examples include funding wells, schools, Qur'an printing, or digital learning platforms that keep benefiting people.</p><p>Many families establish waqf endowments or sponsor micro-projects in memory of loved ones, creating an endless investment in the afterlife.</p>"""),
            ("How important is intention when giving?", """<p><strong>The Prophet SAW taught that actions are rewarded by intentions.</strong> Before giving, believers pause to remember Allah, banish thoughts of self-promotion, and remind themselves that charity is ultimately about Him.</p><p>A sincere niyyah transforms even a small coin, while a corrupt niyyah empties outwardly impressive donations of any lasting reward.</p>"""),
            ("Is charity limited to money?", """<p><strong>No. Smiles, kind words, teaching skills, mentoring youth, donating time, or using influence for justice are all forms of sadaqah.</strong></p><p>This expansive definition ensures that every believer, regardless of income, can participate in building a compassionate society.</p>"""),
            ("Should charity be public or private?", """<p><strong>The Qur'an praises both discreet and public giving.</strong> Secret charity protects sincerity and the recipient's dignity, while public campaigns can inspire others and normalize generosity.</p><p>The key is to check one's ego: if publicity feeds pride, keep it private; if it fuels communal good, share it responsibly.</p>"""),
            ("How does charity respond to emergencies?", """<p><strong>In times of war, famine, or natural disasters, immediate aid can mean the difference between life and death.</strong> Islamic history is full of examples where caravans of aid crossed continents in response to a single distress call.</p><p>Modern Muslims partner with credible relief organizations, combine local fundraisers with digital campaigns, and remain engaged beyond the news cycle.</p>"""),
            ("How do we avoid fostering dependency?", """<p><strong>Islamic charity seeks to empower rather than perpetually sustain.</strong> Programs that provide education, job training, microfinance, and mentorship help recipients become donors themselves.</p><p>Checking in with beneficiaries, asking what they truly need, and respecting their agency prevents paternalism.</p>"""),
            ("What is the social impact of charity?", """<p><strong>Charity is an engine of social justice.</strong> It reduces inequality, diffuses resentment, and heals hearts that might otherwise feel abandoned.</p><p>Communities that normalize giving often enjoy lower crime, stronger masjid participation, and a culture of mutual reliance that no policy alone can create.</p>"""),
            ("How can families nurture generosity in children?", """<p><strong>Invite children to help count coins, deliver food baskets, or choose which cause to support.</strong> Let them witness gratitude from recipients and celebrate small acts of kindness.</p><p>Storytelling about the companions' generosity and keeping sadaqah jars in the home cultivate lasting habits.</p>"""),
            ("How has technology changed giving?", """<p><strong>Automation, crowdfunding, and transparent dashboards make it easier to give consistently and track impact.</strong></p><p>Still, Muslims are urged to vet organizations carefully, read annual reports, and prioritize groups with trustworthy governance.</p>"""),
            ("What if someone feels donor fatigue?", """<p><strong>It is normal to feel overwhelmed by constant appeals.</strong> Setting a realistic budget, diversifying causes, and remembering the eternal payoff renews motivation.</p><p>Rotate between monetary and non-monetary sadaqah, and take time to reflect on how Allah has already repaid your past giving.</p>"""),
            ("Which du'a can increase generosity?", """<p><strong>The Prophet SAW would supplicate, 'O Allah, grant me a heart that is content and a tongue that remembers You.'</strong> Many also recite, 'Allahumma inni a'udhu bika minal hammi wal hazan...' to remove anxieties about provision.</p><p>Combining du'a with concrete budgeting and accountability partners keeps generosity alive all year.</p>"""),
        ],
    ... etc
